// 10 种最常用语言
export type CountryLang = 'zh' | 'en' | 'es' | 'fr' | 'de' | 'ru' | 'ja' | 'ko' | 'ar' | 'pt';

export const COUNTRY_LANG_OPTIONS: { value: CountryLang; label: string }[] = [
  { value: 'zh', label: '中文' },
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
  { value: 'ru', label: 'Русский' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'ar', label: 'العربية' },
  { value: 'pt', label: 'Português' },
];

// 20 个热门国家（可随业务再调）
export const HOT_COUNTRIES: Record<CountryLang, { value: string; label: string }[]> = {
  zh: [
    //欧洲
    { value: 'uk', label: '英国' }, 
    { value: 'germany', label: '德国' }, 
    { value: 'france', label: '法国' }, 
    { value: 'italy', label: '意大利' }, 
    { value: 'spain', label: '西班牙' }, 
    { value: 'portugal', label: '葡萄牙' }, 
    { value: 'netherlands', label: '荷兰' }, 
    { value: 'belgium', label: '比利时' }, 
    { value: 'luxembourg', label: '卢森堡' }, 
    { value: 'switzerland', label: '瑞士' }, 
    { value: 'austria', label: '奥地利' }, 
    { value: 'poland', label: '波兰' }, 
    { value: 'czech_republic', label: '捷克' }, 
    { value: 'slovakia', label: '斯洛伐克' }, 
    { value: 'hungary', label: '匈牙利' }, 
    { value: 'romania', label: '罗马尼亚' }, 
    { value: 'bulgaria', label: '保加利亚' }, 
    { value: 'greece', label: '希腊' }, 
    { value: 'albania', label: '阿尔巴尼亚' }, 
    { value: 'macedonia', label: '北马其顿' }, 
    { value: 'montenegro', label: '黑山' }, 
    { value: 'serbia', label: '塞尔维亚' }, 
    { value: 'bosnia_herzegovina', label: '波黑' }, 
    { value: 'croatia', label: '克罗地亚' }, 
    { value: 'slovenia', label: '斯洛文尼亚' }, 
    { value: 'russia', label: '俄罗斯' }, 
    { value: 'ukraine', label: '乌克兰' }, 
    { value: 'belarus', label: '白俄罗斯' }, 
    { value: 'moldova', label: '摩尔多瓦' }, 
    { value: 'lithuania', label: '立陶宛' }, 
    { value: 'latvia', label: '拉脱维亚' }, 
    { value: 'estonia', label: '爱沙尼亚' }, 
    { value: 'finland', label: '芬兰' }, 
    { value: 'sweden', label: '瑞典' }, 
    { value: 'norway', label: '挪威' }, 
    { value: 'denmark', label: '丹麦' }, 
    { value: 'iceland', label: '冰岛' }, 
    { value: 'ireland', label: '爱尔兰' }, 
    { value: 'malta', label: '马耳他' }, 
    { value: 'monaco', label: '摩纳哥' }, 
    { value: 'andorra', label: '安道尔' }, 
    { value: 'san_marino', label: '圣马力诺' }, 
    { value: 'vatican', label: '梵蒂冈' }, 
    { value: 'liechtenstein', label: '列支敦士登' }, 
 
   // 北美洲 
   { value: 'usa', label: '美国' }, 
   { value: 'canada', label: '加拿大' }, 
   { value: 'mexico', label: '墨西哥' }, 
   { value: 'guatemala', label: '危地马拉' }, 
   { value: 'belize', label: '伯利兹' }, 
   { value: 'el_salvador', label: '萨尔瓦多' }, 
   { value: 'honduras', label: '洪都拉斯' }, 
   { value: 'nicaragua', label: '尼加拉瓜' }, 
   { value: 'costa_rica', label: '哥斯达黎加' }, 
   { value: 'panama', label: '巴拿马' }, 
   { value: 'cuba', label: '古巴' }, 
   { value: 'jamaica', label: '牙买加' }, 
   { value: 'haiti', label: '海地' }, 
   { value: 'dominican_republic', label: '多米尼加' }, 
   { value: 'bahamas', label: '巴哈马' }, 
   { value: 'barbados', label: '巴巴多斯' }, 
   { value: 'trinidad_tobago', label: '特立尼达和多巴哥' }, 
 
   // 南美洲 
   { value: 'brazil', label: '巴西' }, 
   { value: 'argentina', label: '阿根廷' }, 
   { value: 'chile', label: '智利' }, 
   { value: 'peru', label: '秘鲁' }, 
   { value: 'colombia', label: '哥伦比亚' }, 
   { value: 'venezuela', label: '委内瑞拉' }, 
   { value: 'ecuador', label: '厄瓜多尔' }, 
   { value: 'bolivia', label: '玻利维亚' }, 
   { value: 'paraguay', label: '巴拉圭' }, 
   { value: 'uruguay', label: '乌拉圭' }, 
   { value: 'guyana', label: '圭亚那' }, 
   { value: 'suriname', label: '苏里南' }, 
 
   // 大洋洲 
   { value: 'australia', label: '澳大利亚' }, 
   { value: 'new_zealand', label: '新西兰' }, 
   { value: 'fiji', label: '斐济' }, 
   { value: 'papua_new_guinea', label: '巴布亚新几内亚' }, 
   { value: 'samoa', label: '萨摩亚' }, 
   { value: 'tonga', label: '汤加' }, 
   { value: 'vanuatu', label: '瓦努阿图' }, 
   { value: 'solomon_islands', label: '所罗门群岛' }, 
   { value: 'palau', label: '帕劳' }, 
   { value: 'micronesia', label: '密克罗尼西亚' }, 
   { value: 'marshall_islands', label: '马绍尔群岛' }, 
   { value: 'kiribati', label: '基里巴斯' }, 
   { value: 'nauru', label: '瑙鲁' }, 
   { value: 'tuvalu', label: '图瓦卢' }, 
 
   // 非洲 
   { value: 'south_africa', label: '南非' }, 
   { value: 'egypt', label: '埃及' }, 
   { value: 'nigeria', label: '尼日利亚' }, 
   { value: 'kenya', label: '肯尼亚' }, 
   { value: 'ethiopia', label: '埃塞俄比亚' }, 
   { value: 'ghana', label: '加纳' }, 
   { value: 'morocco', label: '摩洛哥' }, 
   { value: 'algeria', label: '阿尔及利亚' }, 
   { value: 'tunisia', label: '突尼斯' }, 
   { value: 'libya', label: '利比亚' }, 
   { value: 'sudan', label: '苏丹' }, 
   { value: 'south_sudan', label: '南苏丹' }, 
   { value: 'chad', label: '乍得' }, 
   { value: 'niger', label: '尼日尔' }, 
   { value: 'mali', label: '马里' }, 
   { value: 'burkina_faso', label: '布基纳法索' }, 
   { value: 'senegal', label: '塞内加尔' }, 
   { value: 'guinea', label: '几内亚' }, 
   { value: 'sierra_leone', label: '塞拉利昂' }, 
   { value: 'liberia', label: '利比里亚' }, 
   { value: 'ivory_coast', label: '科特迪瓦' }, 
   { value: 'togo', label: '多哥' }, 
   { value: 'benin', label: '贝宁' }, 
   { value: 'cameroon', label: '喀麦隆' }, 
   { value: 'central_african_republic', label: '中非共和国' }, 
   { value: 'equatorial_guinea', label: '赤道几内亚' }, 
   { value: 'gabon', label: '加蓬' }, 
   { value: 'congo', label: '刚果共和国' }, 
   { value: 'drc', label: '刚果民主共和国' }, 
   { value: 'angola', label: '安哥拉' }, 
   { value: 'zambia', label: '赞比亚' }, 
   { value: 'zimbabwe', label: '津巴布韦' }, 
   { value: 'botswana', label: '博茨瓦纳' }, 
   { value: 'namibia', label: '纳米比亚' }, 
   { value: 'lesotho', label: '莱索托' }, 
   { value: 'swaziland', label: '斯威士兰' }, 
   { value: 'mozambique', label: '莫桑比克' }, 
   { value: 'malawi', label: '马拉维' }, 
   { value: 'tanzania', label: '坦桑尼亚' }, 
   { value: 'uganda', label: '乌干达' }, 
   { value: 'rwanda', label: '卢旺达' }, 
   { value: 'burundi', label: '布隆迪' }, 
   { value: 'somalia', label: '索马里' }, 
   { value: 'djibouti', label: '吉布提' }, 
   { value: 'eritrea', label: '厄立特里亚' }, 
   { value: 'madagascar', label: '马达加斯加' }, 
   { value: 'mauritius', label: '毛里求斯' }, 
   { value: 'seychelles', label: '塞舌尔' }, 
   { value: 'comoros', label: '科摩罗' }, 
   { value: 'cape_verde', label: '佛得角' }, 
   { value: 'sao_tome_principe', label: '圣多美和普林西比' }, 
   { value: 'gambia', label: '冈比亚' }, 
   { value: 'guinea_bissau', label: '几内亚比绍' }
  ],
  en: [
    { value: 'uk', label: 'United Kingdom' },
    { value: 'germany', label: 'Germany' },
    { value: 'france', label: 'France' },
    { value: 'italy', label: 'Italy' },
    { value: 'spain', label: 'Spain' },
    { value: 'portugal', label: 'Portugal' },
    { value: 'netherlands', label: 'Netherlands' },
    { value: 'belgium', label: 'Belgium' },
    { value: 'luxembourg', label: 'Luxembourg' },
    { value: 'switzerland', label: 'Switzerland' },
    { value: 'austria', label: 'Austria' },
    { value: 'poland', label: 'Poland' },
    { value: 'czech_republic', label: 'Czech Republic' },
    { value: 'slovakia', label: 'Slovakia' },
    { value: 'hungary', label: 'Hungary' },
    { value: 'romania', label: 'Romania' },
    { value: 'bulgaria', label: 'Bulgaria' },
    { value: 'greece', label: 'Greece' },
    { value: 'albania', label: 'Albania' },
    { value: 'macedonia', label: 'North Macedonia' },
    { value: 'montenegro', label: 'Montenegro' },
    { value: 'serbia', label: 'Serbia' },
    { value: 'bosnia_herzegovina', label: 'Bosnia and Herzegovina' },
    { value: 'croatia', label: 'Croatia' },
    { value: 'slovenia', label: 'Slovenia' },
    { value: 'russia', label: 'Russia' },
    { value: 'ukraine', label: 'Ukraine' },
    { value: 'belarus', label: 'Belarus' },
    { value: 'moldova', label: 'Moldova' },
    { value: 'lithuania', label: 'Lithuania' },
    { value: 'latvia', label: 'Latvia' },
    { value: 'estonia', label: 'Estonia' },
    { value: 'finland', label: 'Finland' },
    { value: 'sweden', label: 'Sweden' },
    { value: 'norway', label: 'Norway' },
    { value: 'denmark', label: 'Denmark' },
    { value: 'iceland', label: 'Iceland' },
    { value: 'ireland', label: 'Ireland' },
    { value: 'malta', label: 'Malta' },
    { value: 'monaco', label: 'Monaco' },
    { value: 'andorra', label: 'Andorra' },
    { value: 'san_marino', label: 'San Marino' },
    { value: 'vatican', label: 'Vatican City' },
    { value: 'liechtenstein', label: 'Liechtenstein' },

    // North America
    { value: 'usa', label: 'United States' },
    { value: 'canada', label: 'Canada' },
    { value: 'mexico', label: 'Mexico' },
    { value: 'guatemala', label: 'Guatemala' },
    { value: 'belize', label: 'Belize' },
    { value: 'el_salvador', label: 'El Salvador' },
    { value: 'honduras', label: 'Honduras' },
    { value: 'nicaragua', label: 'Nicaragua' },
    { value: 'costa_rica', label: 'Costa Rica' },
    { value: 'panama', label: 'Panama' },
    { value: 'cuba', label: 'Cuba' },
    { value: 'jamaica', label: 'Jamaica' },
    { value: 'haiti', label: 'Haiti' },
    { value: 'dominican_republic', label: 'Dominican Republic' },
    { value: 'bahamas', label: 'Bahamas' },
    { value: 'barbados', label: 'Barbados' },
    { value: 'trinidad_tobago', label: 'Trinidad and Tobago' },

    // South America
    { value: 'brazil', label: 'Brazil' },
    { value: 'argentina', label: 'Argentina' },
    { value: 'chile', label: 'Chile' },
    { value: 'peru', label: 'Peru' },
    { value: 'colombia', label: 'Colombia' },
    { value: 'venezuela', label: 'Venezuela' },
    { value: 'ecuador', label: 'Ecuador' },
    { value: 'bolivia', label: 'Bolivia' },
    { value: 'paraguay', label: 'Paraguay' },
    { value: 'uruguay', label: 'Uruguay' },
    { value: 'guyana', label: 'Guyana' },
    { value: 'suriname', label: 'Suriname' },

    // Oceania
    { value: 'australia', label: 'Australia' },
    { value: 'new_zealand', label: 'New Zealand' },
    { value: 'fiji', label: 'Fiji' },
    { value: 'papua_new_guinea', label: 'Papua New Guinea' },
    { value: 'samoa', label: 'Samoa' },
    { value: 'tonga', label: 'Tonga' },
    { value: 'vanuatu', label: 'Vanuatu' },
    { value: 'solomon_islands', label: 'Solomon Islands' },
    { value: 'palau', label: 'Palau' },
    { value: 'micronesia', label: 'Micronesia' },
    { value: 'marshall_islands', label: 'Marshall Islands' },
    { value: 'kiribati', label: 'Kiribati' },
    { value: 'nauru', label: 'Nauru' },
    { value: 'tuvalu', label: 'Tuvalu' },

    // Africa
    { value: 'south_africa', label: 'South Africa' },
    { value: 'egypt', label: 'Egypt' },
    { value: 'nigeria', label: 'Nigeria' },
    { value: 'kenya', label: 'Kenya' },
    { value: 'ethiopia', label: 'Ethiopia' },
    { value: 'ghana', label: 'Ghana' },
    { value: 'morocco', label: 'Morocco' },
    { value: 'algeria', label: 'Algeria' },
    { value: 'tunisia', label: 'Tunisia' },
    { value: 'libya', label: 'Libya' },
    { value: 'sudan', label: 'Sudan' },
    { value: 'south_sudan', label: 'South Sudan' },
    { value: 'chad', label: 'Chad' },
    { value: 'niger', label: 'Niger' },
    { value: 'mali', label: 'Mali' },
    { value: 'burkina_faso', label: 'Burkina Faso' },
    { value: 'senegal', label: 'Senegal' },
    { value: 'guinea', label: 'Guinea' },
    { value: 'sierra_leone', label: 'Sierra Leone' },
    { value: 'liberia', label: 'Liberia' },
    { value: 'ivory_coast', label: 'Ivory Coast' },
    { value: 'togo', label: 'Togo' },
    { value: 'benin', label: 'Benin' },
    { value: 'cameroon', label: 'Cameroon' },
    { value: 'central_african_republic', label: 'Central African Republic' },
    { value: 'equatorial_guinea', label: 'Equatorial Guinea' },
    { value: 'gabon', label: 'Gabon' },
    { value: 'congo', label: 'Republic of the Congo' },
    { value: 'drc', label: 'Democratic Republic of the Congo' },
    { value: 'angola', label: 'Angola' },
    { value: 'zambia', label: 'Zambia' },
    { value: 'zimbabwe', label: 'Zimbabwe' },
    { value: 'botswana', label: 'Botswana' },
    { value: 'namibia', label: 'Namibia' },
    { value: 'lesotho', label: 'Lesotho' },
    { value: 'swaziland', label: 'Eswatini' },
    { value: 'mozambique', label: 'Mozambique' },
    { value: 'malawi', label: 'Malawi' },
    { value: 'tanzania', label: 'Tanzania' },
    { value: 'uganda', label: 'Uganda' },
    { value: 'rwanda', label: 'Rwanda' },
    { value: 'burundi', label: 'Burundi' },
    { value: 'somalia', label: 'Somalia' },
    { value: 'djibouti', label: 'Djibouti' },
    { value: 'eritrea', label: 'Eritrea' },
    { value: 'madagascar', label: 'Madagascar' },
    { value: 'mauritius', label: 'Mauritius' },
    { value: 'seychelles', label: 'Seychelles' },
    { value: 'comoros', label: 'Comoros' },
    { value: 'cape_verde', label: 'Cape Verde' },
    { value: 'sao_tome_principe', label: 'Sao Tome and Principe' },
    { value: 'gambia', label: 'Gambia' },
    { value: 'guinea_bissau', label: 'Guinea-Bissau' }
  ],
  es: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'Estados Unidos' },
    { value: 'JP', label: 'Japón' },
    { value: 'KR', label: 'Corea del Sur' },
    { value: 'SG', label: 'Singapur' },
    { value: 'CA', label: 'Canadá' },
    { value: 'AU', label: 'Australia' },
    { value: 'GB', label: 'Reino Unido' },
    { value: 'FR', label: 'Francia' },
    { value: 'DE', label: 'Alemania' },
    { value: 'IT', label: 'Italia' },
    { value: 'ES', label: 'España' },
    { value: 'RU', label: 'Rusia' },
    { value: 'BR', label: 'Brasil' },
    { value: 'MX', label: 'México' },
    { value: 'IN', label: 'India' },
    { value: 'TH', label: 'Tailandia' },
    { value: 'MY', label: 'Malasia' },
    { value: 'NL', label: 'Países Bajos' },
    { value: 'SE', label: 'Suecia' },
  ],
  fr: [
    { value: 'CN', label: 'Chine' },
    { value: 'US', label: 'États-Unis' },
    { value: 'JP', label: 'Japon' },
    { value: 'KR', label: 'Corée du Sud' },
    { value: 'SG', label: 'Singapour' },
    { value: 'CA', label: 'Canada' },
    { value: 'AU', label: 'Australie' },
    { value: 'GB', label: 'Royaume-Uni' },
    { value: 'FR', label: 'France' },
    { value: 'DE', label: 'Allemagne' },
    { value: 'IT', label: 'Italie' },
    { value: 'ES', label: 'Espagne' },
    { value: 'RU', label: 'Russie' },
    { value: 'BR', label: 'Brésil' },
    { value: 'MX', label: 'Mexique' },
    { value: 'IN', label: 'Inde' },
    { value: 'TH', label: 'Thaïlande' },
    { value: 'MY', label: 'Malaisie' },
    { value: 'NL', label: 'Pays-Bas' },
    { value: 'SE', label: 'Suède' },
  ],
  de: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'Vereinigte Staaten' },
    { value: 'JP', label: 'Japan' },
    { value: 'KR', label: 'Südkorea' },
    { value: 'SG', label: 'Singapur' },
    { value: 'CA', label: 'Kanada' },
    { value: 'AU', label: 'Australien' },
    { value: 'GB', label: 'Vereinigtes Königreich' },
    { value: 'FR', label: 'Frankreich' },
    { value: 'DE', label: 'Deutschland' },
    { value: 'IT', label: 'Italien' },
    { value: 'ES', label: 'Spanien' },
    { value: 'RU', label: 'Russland' },
    { value: 'BR', label: 'Brasilien' },
    { value: 'MX', label: 'Mexiko' },
    { value: 'IN', label: 'Indien' },
    { value: 'TH', label: 'Thailand' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'NL', label: 'Niederlande' },
    { value: 'SE', label: 'Schweden' },
  ],
  ru: [
    { value: 'CN', label: 'Китай' },
    { value: 'US', label: 'США' },
    { value: 'JP', label: 'Япония' },
    { value: 'KR', label: 'Южная Корея' },
    { value: 'SG', label: 'Сингапур' },
    { value: 'CA', label: 'Канада' },
    { value: 'AU', label: 'Австралия' },
    { value: 'GB', label: 'Великобритания' },
    { value: 'FR', label: 'Франция' },
    { value: 'DE', label: 'Германия' },
    { value: 'IT', label: 'Италия' },
    { value: 'ES', label: 'Испания' },
    { value: 'RU', label: 'Россия' },
    { value: 'BR', label: 'Бразилия' },
    { value: 'MX', label: 'Мексика' },
    { value: 'IN', label: 'Индия' },
    { value: 'TH', label: 'Таиланд' },
    { value: 'MY', label: 'Малайзия' },
    { value: 'NL', label: 'Нидерланды' },
    { value: 'SE', label: 'Швеция' },
  ],
  ja: [
    { value: 'CN', label: '中国' },
    { value: 'US', label: 'アメリカ合衆国' },
    { value: 'JP', label: '日本' },
    { value: 'KR', label: '韓国' },
    { value: 'SG', label: 'シンガポール' },
    { value: 'CA', label: 'カナダ' },
    { value: 'AU', label: 'オーストラリア' },
    { value: 'GB', label: 'イギリス' },
    { value: 'FR', label: 'フランス' },
    { value: 'DE', label: 'ドイツ' },
    { value: 'IT', label: 'イタリア' },
    { value: 'ES', label: 'スペイン' },
    { value: 'RU', label: 'ロシア' },
    { value: 'BR', label: 'ブラジル' },
    { value: 'MX', label: 'メキシコ' },
    { value: 'IN', label: 'インド' },
    { value: 'TH', label: 'タイ' },
    { value: 'MY', label: 'マレーシア' },
    { value: 'NL', label: 'オランダ' },
    { value: 'SE', label: 'スウェーデン' },
  ],
  ko: [
    { value: 'CN', label: '중국' },
    { value: 'US', label: '미국' },
    { value: 'JP', label: '일본' },
    { value: 'KR', label: '한국' },
    { value: 'SG', label: '싱가포르' },
    { value: 'CA', label: '캐나다' },
    { value: 'AU', label: '호주' },
    { value: 'GB', label: '영국' },
    { value: 'FR', label: '프랑스' },
    { value: 'DE', label: '독일' },
    { value: 'IT', label: '이탈리아' },
    { value: 'ES', label: '스페인' },
    { value: 'RU', label: '러시아' },
    { value: 'BR', label: '브라질' },
    { value: 'MX', label: '멕시코' },
    { value: 'IN', label: '인도' },
    { value: 'TH', label: '태국' },
    { value: 'MY', label: '말레이시아' },
    { value: 'NL', label: '네덜란드' },
    { value: 'SE', label: '스웨덴' },
  ],
  ar: [
    { value: 'CN', label: 'الصين' },
    { value: 'US', label: 'الولايات المتحدة' },
    { value: 'JP', label: 'اليابان' },
    { value: 'KR', label: 'كوريا الجنوبية' },
    { value: 'SG', label: 'سنغافورة' },
    { value: 'CA', label: 'كندا' },
    { value: 'AU', label: 'أستراليا' },
    { value: 'GB', label: 'المملكة المتحدة' },
    { value: 'FR', label: 'فرنسا' },
    { value: 'DE', label: 'ألمانيا' },
    { value: 'IT', label: 'إيطاليا' },
    { value: 'ES', label: 'إسبانيا' },
    { value: 'RU', label: 'روسيا' },
    { value: 'BR', label: 'البرازيل' },
    { value: 'MX', label: 'المكسيك' },
    { value: 'IN', label: 'الهند' },
    { value: 'TH', label: 'تايلاند' },
    { value: 'MY', label: 'ماليزيا' },
    { value: 'NL', label: 'هولندا' },
    { value: 'SE', label: 'السويد' },
  ],
  pt: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'Estados Unidos' },
    { value: 'JP', label: 'Japão' },
    { value: 'KR', label: 'Coreia do Sul' },
    { value: 'SG', label: 'Singapura' },
    { value: 'CA', label: 'Canadá' },
    { value: 'AU', label: 'Austrália' },
    { value: 'GB', label: 'Reino Unido' },
    { value: 'FR', label: 'França' },
    { value: 'DE', label: 'Alemanha' },
    { value: 'IT', label: 'Itália' },
    { value: 'ES', label: 'Espanha' },
    { value: 'RU', label: 'Rússia' },
    { value: 'BR', label: 'Brasil' },
    { value: 'MX', label: 'México' },
    { value: 'IN', label: 'Índia' },
    { value: 'TH', label: 'Tailândia' },
    { value: 'MY', label: 'Malásia' },
    { value: 'NL', label: 'Países Baixos' },
    { value: 'SE', label: 'Suécia' },
  ],
};

// 默认语言为中文
export const DEFAULT_COUNTRY_LANG: CountryLang = 'zh';